String=input("Enter String:-")
print(len(String))
print(String.upper())
print(String.lower())
print(String.capitalize())
print(String.casefold())
print(String.title())
print(String.count("s"))
print(String.find("m"))

my_name=input("Enter name:-")
age=int(input("Enter your age:-"))
add=str(input("Enter your address:-"))
div=input("Enter your div:-")
department=str(input("Enter your Department name:-"))
print(f"My name is {my_name}.\nMy age is {age}.\nI am from {add}.\nMy department name is {department} and div is {div}.")